# Generated by Django 4.2.1 on 2023-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('button_text', models.CharField(max_length=40, verbose_name='Текст кнопки')),
                ('button_path', models.CharField(max_length=300, verbose_name='Ссылка, на которую ссылается кнопка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('sequence', models.IntegerField(verbose_name='Очередность слайда')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
