# Generated by Django 4.2.1 on 2023-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kitchen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='bedroom/', verbose_name='Картинка')),
                ('sequence', models.IntegerField(verbose_name="Очередность 'элемента'")),
            ],
            options={
                'verbose_name': 'Спальня',
                'verbose_name_plural': 'Спальни',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='furniture/', verbose_name='Картинка')),
                ('sequence', models.IntegerField(verbose_name="Очередность 'элемента'")),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='wardrobe/', verbose_name='Картинка')),
                ('sequence', models.IntegerField(verbose_name="Очередность 'элемента'")),
            ],
            options={
                'verbose_name': 'Гардеробная',
                'verbose_name_plural': 'Гардеробные',
            },
        ),
    ]
