# Generated by Django 4.2.1 on 2023-05-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
